# Generated by Django 3.2.9 on 2021-12-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
