# Generated by Django 3.2.9 on 2021-12-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recurring_product',
            field=models.TextField(default='[]'),
        ),
    ]
