# Generated by Django 3.2.9 on 2021-12-08 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locality', '0002_auto_20211129_1951'),
        ('user', '0002_auto_20211129_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locality.locality'),
        ),
    ]
