# Generated by Django 3.2.9 on 2021-11-29 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locality', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locality',
            options={'verbose_name_plural': 'Localities'},
        ),
        migrations.AlterModelTable(
            name='locality',
            table='vj_locality',
        ),
    ]
