# Generated by Django 3.2.9 on 2021-12-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurring_product', '0003_alter_recurringproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringproduct',
            name='product',
            field=models.TextField(),
        ),
    ]
