# Generated by Django 3.2.9 on 2021-11-21 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('contact', models.CharField(max_length=13)),
                ('house_number', models.CharField(max_length=7)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localities.localities')),
            ],
        ),
    ]
