# Generated by Django 3.2.9 on 2021-11-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='desciption',
            new_name='description',
        ),
    ]
